name: Translate News Headlines

on:
  workflow_dispatch:  # Manual trigger
  schedule:
    - cron: '40 3 * * *'  # This will run daily at 9:10 AM IST (UTC +5:30)

jobs:
  translate:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12.5'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tastranslate

    - name: Run translation script
      run: |
        python networking/translate_news.py

    - name: Commit translated files
      run: |
        git config --global user.name "suryadip2008"
        git config --global user.email "suryadip.2008@gmail.com"
        git add networking/news_*.json
        git commit -m "bot(scripts): Translations"
        git push
