name: Update and Translate News Headlines Daily

on:
  schedule:
    - cron: '30 3 * * *'  # Runs daily at 9:00 AM IST (3:30 AM UTC)
  workflow_dispatch:  # Allows manual trigger

jobs:
  update-news:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12.5'

    - name: Install dependencies
      run: |
        pip install requests

    - name: Run the script to update news.json
      run: python networking/update_news.py

    - name: Commit changes
      run: |
        git config --local user.name "suryadip2008"
        git config --local user.email "suryadip.2008@gmail.com"
        git add networking/news.json
        git commit -m "bot(scripts): Daily News Update"
        git push

  translate-news:
    runs-on: ubuntu-latest
    needs: update-news  # This ensures the second job only runs after update-news finishes

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12.5'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tastranslate

    - name: Run translation script
      run: |
        python networking/translate_news.py

    - name: Commit translated files
      run: |
        git config --global user.name "suryadip2008"
        git config --global user.email "suryadip.2008@gmail.com"
        git add networking/news_*.json
        git commit -m "bot(scripts): Translate News"
        git push
